// Generated by CoffeeScript 1.7.1
(function() {
  if (Dropbox.isBrowserSupported) {
    $('.dropbox._button').show().click(function() {
      return Dropbox.choose({
        success: fs(function() {
          var f, _i, _len;
          for (_i = 0, _len = fs.length; _i < _len; _i++) {
            f = fs[_i];
            files.push({
              dropbox_url: f.link,
              file_name: f.name
            });
          }
          updateFilesList;
          showTick(true);
          toggleThePrintMode;
          return $('.print._button').removeClass('_disabled');
        }),
        linkType: "direct",
        multiselect: true,
        extensions: ['.pdf']
      });
    });
  }

}).call(this);
