// Generated by CoffeeScript 1.7.1
(function() {
  var showError;

  showError = function(field) {
    field.addClass('_error');
    return field.click(function(event) {
      $(this).removeClass('_error');
      return $(this).unbind(event);
    });
  };

  jQuery.fn.check = function() {
    var def, max, min, v;
    if ($(this).hasClass('_numberField')) {
      min = $(this).attr('min');
      max = $(this).attr('max');
      def = $(this).attr('default');
      v = parseInt($(this).val()) || def || min || 1;
      v = v >= min ? v : min;
      return $(this).val(v);
    }
  };

  jQuery.fn.validate = function() {
    var form, result;
    result = {};
    form = $(this);
    form.find('input').each(function(e) {
      return e.removeClass('_error');
    });
    form.find('input').each(function(e) {
      if (!e.hasClass('_numberField')) {
        if (e.hasClass('nonempty') && $(this).val() === "") {
          result['error'] = true;
          return showError(e);
        } else {
          return result[e.attr('name')] = e.val();
        }
      }
    });
    form.find('._checkbox').each(function(e) {
      return result[e.attr('name')] = e.hasClass('_checked');
    });
    form.find('._numberField').each(function(e) {
      var value;
      if (value = parseInt(e.val()) && (!e.attr('min') || value >= parseInt(e.attr('min'))) && (!e.attr('max') || value <= parseInt(e.attr('max')))) {
        return result[e.attr('name')] = value;
      } else {
        showError(e);
        return result['error'] = true;
      }
    });
    form.find('._radioGroup').each(function(g) {
      return result[g.attr('name')] = g.find('._radiobox._checked').attr('name');
    });
    return result;
  };

  $(function() {
    $('._checkbox').click(function() {
      event.preventDefault();
      if ($(this).hasClass('_checked')) {
        $(this).removeClass('_checked').addClass('_unchecked');
      } else {
        $(this).removeClass('_unchecked').addClass('_checked');
      }
      return $(this).trigger('valueChanged');
    });
    $('._radiobox').click(function() {
      event.preventDefault();
      if ($(this).hasClass('_unchecked')) {
        $(this).parents('._radioGroup').children('._radiobox').removeClass('_checked').addClass('_unchecked');
        $(this).removeClass('_unchecked').addClass('_checked');
        return $(this).parents('._radioGroup').trigger('valueChanged');
      }
    });
    $('._label').click(function() {
      event.preventDefault();
      return $('.' + $(this).attr('for')).click();
    });
    $('form').attr('onSubmit', "return false");
    $('.submit._button').click(function() {
      return $(this).parents('form').submit();
    });
    return $('input._numberField').change(function() {
      return $(this).check();
    });
  });

}).call(this);
