// Generated by CoffeeScript 1.7.1
(function() {
  var sendPrint;

  sendPrint = function() {
    var form;
    form = $('#printForm').validate();
    if (!form['error']) {
      form['gaspar'] = GASPAR;
      form['files'] = files;
      $('.print._button').addClass('_disabled');
      return $.ajax('print.php', {
        type: "POST",
        data: form,
        success: function(response) {
          var e, rep;
          rep = (function() {
            try {
              return JSON.parse(response);
            } catch (_error) {
              e = _error;
              return {
                'error_code': -1
              };
            }
          })();
          switch (rep['error_code']) {
            case 0:
              message('The document' + (files.length > 1 ? 's were' : ' was') + ' sent to the printer');
              return toggleTheUploadMode("UPLOAD NEW FILES");
            case 2:
              return message('A problem occured with dropbox');
            case 3:
              showError($('.gaspar, .password'));
              return message('Please check your credentials');
            default:
              return message('An error occured while printing the document...');
          }
        },
        error: function() {
          return message('An error occured while printing the document...');
        },
        complete: function() {
          var files;
          files = [];
          return $('.print._button').removeClass('_disabled');
        }
      });
    }
  };

  $(function() {
    return $('.print._button').click(sendPrint);
  });

}).call(this);
