// Generated by CoffeeScript 1.7.1
(function() {
  var files, updateFilesList, uploadFile;

  files = [];

  updateFilesList = function() {
    var f, name, _i, _len;
    $('.message').html("<ul id='files'></ul>");
    for (_i = 0, _len = files.length; _i < _len; _i++) {
      f = files[_i];
      name = name.length < 30 ? file['file_name'] : file['file_name'].slice(0, 15) + "..." + file['file_name'].slice(-14);
      $('#files').append("<li><span class='removeFile'>" + name + "</span></li>");
    }
    if (files.length > 1) {
      $('.all._radiobox').click();
      $('._radioGroup.selection').hide(centerDialog);
    } else if ($('._radioGroup.selection').css('display') === 'none') {
      $('._radioGroup.selection').show(centerDialog);
    }
    centerCloud();
    return $('span.removeFile').click(function() {
      files.splice($(this).index(), 1);
      if (files.length === 0) {
        toggleTheUploadMode();
        showTick(false);
      }
      return updateFilesList();
    });
  };

  uploadFile = function(file) {
    var fd, xhr;
    toggleThePrintMode();
    $('.print._button').addClass('_disabled');
    fd = new FormData();
    fd.append('file', file);
    xhr = new XMLHttpRequest();
    xhr.addEventListener("loadend", function(e) {
      var rep;
      rep = (function() {
        try {
          return JSON.parse(e.currentTarget.responseText);
        } catch (_error) {
          e = _error;
          return {
            'error_code': -1
          };
        }
      })();
      if (rep['error_code'] === 0) {
        showTick(true);
        files.push({
          file_name: rep['file_name'],
          server_file_name: rep['server_file_name']
        });
        updateFilesList;
        return $('.print._button').removeClass('_disabled');
      } else {
        showTick(false);
        message('An error occured, please retry...');
        return toggleTheUploadMode("UPLOAD YOUR FILES");
      }
    });
    xhr.open("POST", "upload_file.php");
    return xhr.send(fd);
  };

}).call(this);
